CREATE TABLE [dbo].[ListSurveyRespondent] (
    [ListCompanyResponseId] INT IDENTITY (1, 1) NOT NULL,
    [ListCompanyId]         INT NOT NULL,
    [RespondentKey]         INT NOT NULL,
    [Response_1]            INT NULL,
    [Response_2]            INT NULL,
    [Response_3]            INT NULL,
    [Response_4]            INT NULL,
    [Response_5]            INT NULL,
    [Response_6]            INT NULL,
    [Response_7]            INT NULL,
    [Response_8]            INT NULL,
    [Response_9]            INT NULL,
    [Response_10]           INT NULL,
    [Response_11]           INT NULL,
    [Response_12]           INT NULL,
    [Response_13]           INT NULL,
    [Response_14]           INT NULL,
    [Response_15]           INT NULL,
    [Response_16]           INT NULL,
    [Response_17]           INT NULL,
    [Response_18]           INT NULL,
    [Response_19]           INT NULL,
    [Response_20]           INT NULL,
    [Response_21]           INT NULL,
    [Response_22]           INT NULL,
    [Response_23]           INT NULL,
    [Response_24]           INT NULL,
    [Response_25]           INT NULL,
    [Response_26]           INT NULL,
    [Response_27]           INT NULL,
    [Response_28]           INT NULL,
    [Response_29]           INT NULL,
    [Response_30]           INT NULL,
    [Response_31]           INT NULL,
    [Response_32]           INT NULL,
    [Response_33]           INT NULL,
    [Response_34]           INT NULL,
    [Response_35]           INT NULL,
    [Response_36]           INT NULL,
    [Response_37]           INT NULL,
    [Response_38]           INT NULL,
    [Response_39]           INT NULL,
    [Response_40]           INT NULL,
    [Response_41]           INT NULL,
    [Response_42]           INT NULL,
    [Response_43]           INT NULL,
    [Response_44]           INT NULL,
    [Response_45]           INT NULL,
    [Response_46]           INT NULL,
    [Response_47]           INT NULL,
    [Response_48]           INT NULL,
    [Response_49]           INT NULL,
    [Response_50]           INT NULL,
    [Response_51]           INT NULL,
    [Response_52]           INT NULL,
    [Response_53]           INT NULL,
    [Response_54]           INT NULL,
    [Response_55]           INT NULL,
    [Response_56]           INT NULL,
    [Response_57]           INT NULL,
    [Response_672]          INT NULL,
    [Response_12211]        INT NULL,
    [Response_12212]        INT NULL,
    [Response_12213]        INT NULL,
    [Response_12214]        INT NULL,
    [Response_12215]        INT NULL,
    CONSTRAINT [PK_ListSurveyRespondent] PRIMARY KEY CLUSTERED ([ListCompanyResponseId] ASC),
    CONSTRAINT [FK_ListSurveyRespondent_ListCompany] FOREIGN KEY ([ListCompanyId]) REFERENCES [dbo].[ListCompany] ([ListCompanyId])
);


GO
CREATE NONCLUSTERED INDEX [IDX_ListSurveyRespondent_ListCompanyId]
    ON [dbo].[ListSurveyRespondent]([ListCompanyId] ASC);

