
'Option Explicit On
'Option Strict On

'Imports MongoDB.Bson
'Imports MongoDB.Bson.Serialization.Attributes
'Public Class Contact
'    Public Property Id As ObjectId ' Mongo Id for this Job
'    'Public Property AffiliateId As String = ""
'    Public Property ClientId As Integer = 0
'    Public Property SF_ContactId As String = "" ' Salesforce Id of Contact object
'    Public Property SF_AccountId As String = "" 'AccountId Salesforce Id of parent Account object
'    Public Property PortalId As String = "" ' Portal_ID__c Unique Id assigned by the portal for this specific contact
'    Public Property ContactId As String = "" ' Guid contact id generated by Atlas when the contact is created
'    Public Property FirstName As String = "" ' FirstName
'    Public Property LastName As String = "" ' LastName
'    Public Property Email As String = "" ' Email
'    Public Property PublicRelationsEmails As Boolean = False ' PUBLIC_RELATIONS__c
'    Public Property MarketingEmails As Boolean = False ' Marketing__c
'    Public Property OperationalEmails As Boolean = False ' Operational__c
'    Public Property PrimaryPortalContact As Boolean = False ' Primary_Certification_Contact__c
'    Public Property IsPortalContact As Boolean = True 'Recognition_Portal_Account__c
'    Public Property PortalUsername As String = "" ' Portal_Username__c
'    Public Property PortalContactBlocked As Boolean = False
'    Public Property ContactChanged As Boolean = False
'    <BsonDateTimeOptions(Kind:=DateTimeKind.Utc)> Public Property LastLoginDate As Date = Nothing
'End Class
