namespace GPTW.ListAutomation.TestUI.Models;

public sealed class ListSurveyRespondentItemModel
{
    public int EngagementId { get; set; }
    public int ClientId { get; set; }
    public string SurveyVersionId { get; set; }
    public int RespondentKey { get; set; }
    public int Response_1 { get; set; }
    public int Response_2 { get; set; }
    public int Response_3 { get; set; }
    public int Response_4 { get; set; }
    public int Response_5 { get; set; }
    public int Response_6 { get; set; }
    public int Response_7 { get; set; }
    public int Response_8 { get; set; }
    public int Response_9 { get; set; }
    public int Response_10 { get; set; }
    public int Response_11 { get; set; }
    public int Response_12 { get; set; }
    public int Response_13 { get; set; }
    public int Response_14 { get; set; }
    public int Response_15 { get; set; }
    public int Response_16 { get; set; }
    public int Response_17 { get; set; }
    public int Response_18 { get; set; }
    public int Response_19 { get; set; }
    public int Response_20 { get; set; }
    public int Response_21 { get; set; }
    public int Response_22 { get; set; }
    public int Response_23 { get; set; }
    public int Response_24 { get; set; }
    public int Response_25 { get; set; }
    public int Response_26 { get; set; }
    public int Response_27 { get; set; }
    public int Response_28 { get; set; }
    public int Response_29 { get; set; }
    public int Response_30 { get; set; }
    public int Response_31 { get; set; }
    public int Response_32 { get; set; }
    public int Response_33 { get; set; }
    public int Response_34 { get; set; }
    public int Response_35 { get; set; }
    public int Response_36 { get; set; }
    public int Response_37 { get; set; }
    public int Response_38 { get; set; }
    public int Response_39 { get; set; }
    public int Response_40 { get; set; }
    public int Response_41 { get; set; }
    public int Response_42 { get; set; }
    public int Response_43 { get; set; }
    public int Response_44 { get; set; }
    public int Response_45 { get; set; }
    public int Response_46 { get; set; }
    public int Response_47 { get; set; }
    public int Response_48 { get; set; }
    public int Response_49 { get; set; }
    public int Response_50 { get; set; }
    public int Response_51 { get; set; }
    public int Response_52 { get; set; }
    public int Response_53 { get; set; }
    public int Response_54 { get; set; }
    public int Response_55 { get; set; }
    public int Response_56 { get; set; }
    public int Response_57 { get; set; }
    public int Response_672 { get; set; }
    public int Response_12211 { get; set; }
    public int Response_12212 { get; set; }
    public int Response_12213 { get; set; }
    public int Response_12214 { get; set; }
    public int Response_12215 { get; set; }
}
